config/routes.rb
Ideas::Application.routes.draw do

  resources :categories, :except => :show

  resources :projects, :except => :show do
    resources :ideas do
      resources :comments, :only => [:index, :create, :new]
    end

    resources :memberships, :only => [:index, :destroy, :create]
    get '/history' => 'history#index'
    get '/settings' => 'settings#edit', :as => :edit_settings
    post '/settings' => 'settings#update', :as => :update_settings
  end
  post '/membership/update' => 'memberships#update'
  post '/project/update/idea' => 'projects#update_project_idea'
  get '/ideas' => 'ideas#view_all'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get "users/sign_out" => "devise/sessions#destroy"
  end

  match '/incoming_mail' => 'incoming_mail#create'
  match '/new_favorite' => 'favorite_ideas#create', :as => 'new_favorite'
  match '/delete_favorite' => 'favorite_ideas#delete', :as => 'delete_favorite'
  match '/rating' => 'ratings#rate', :as => 'rate_idea'
  root :to => 'front#index'
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  validates :user, :presence => true
  validates :project, :presence => true

  validates_uniqueness_of :project_id, :scope => :user_id
end

app/controllers/memberships_controller.rb
class MembershipsController < SecureController
  def index
    @memberships = current_project.memberships
    @membership = current_project.memberships.build
  end

  def create
    email = params[:membership][:user]
    user = User.find_by_email email
    @membership = Membership.new(:user=> user, :project=> current_project, :collapsed => false)
    
    if @membership.save
      redirect_to :back, :notice => 'Membership was successfully created.'
    else
      redirect_to :back, :alert => "Sorry, couldn't find a user with #{email} as their email address"
    end
  end
  
  def destroy
    membership = Membership.find(params[:id])
    if current_user == membership.user
      redirect_to projects_path
    else
      redirect_to :back, :notice => "User with #{membership.user.email} successfully removed"
    end

    membership.destroy
  end

  def update
    membership = Membership.where(:project_id => params[:project_id], :user_id => current_user).first
    puts membership
    membership.collapsed = params[:collapsed]
    membership.save
    respond_to do |format|
      format.json { render :json => {} }
      format.html { redirect_to :controller => :projects, :action => :index }
    end
  end
end

app/views/memberships/_form.html.haml
= form_for [current_project, @membership], :html => {:class => 'form-stacked'} do |f|
  - if @membership.errors.any?
    #error_explanation
      %h2
        = pluralize(@membership.errors.count, "error") 
        prohibited this project from being saved:
      %ul
        - @membership.errors.full_messages.each do |msg|
          %li
            = msg

  %fieldset
    = f.label :user, "Enter collaborator's email:"
    = f.text_field :user, :value => (f.object.user.blank? ? '' : f.object.user.email)

  = f.submit 'Add Collaborator', :class => 'btn btn-primary'

app/views/memberships/index.html.haml
%h2 Collaborators

%table
  - @memberships.each do |membership|
    %tr
      %td= membership.user.email
      %td= link_to 'Remove', [current_project, membership], confirm: 'Are you sure?', :method => :delete

= render :partial => 'form'

app/views/memberships/new.html.haml
%h2 New Collaborator

= render 'form'

= link_to 'Back', project_memberships_path