config/routes.rb
Ideas::Application.routes.draw do

  resources :categories, :except => :show

  resources :projects, :except => :show do
    resources :ideas do
      resources :comments, :only => [:index, :create, :new]
    end

    resources :memberships, :only => [:index, :destroy, :create]
    get '/history' => 'history#index'
    get '/settings' => 'settings#edit', :as => :edit_settings
    post '/settings' => 'settings#update', :as => :update_settings
  end
  post '/membership/update' => 'memberships#update'
  post '/project/update/idea' => 'projects#update_project_idea'
  get '/ideas' => 'ideas#view_all'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get "users/sign_out" => "devise/sessions#destroy"
  end

  match '/incoming_mail' => 'incoming_mail#create'
  match '/new_favorite' => 'favorite_ideas#create', :as => 'new_favorite'
  match '/delete_favorite' => 'favorite_ideas#delete', :as => 'delete_favorite'
  match '/rating' => 'ratings#rate', :as => 'rate_idea'
  root :to => 'front#index'
end

app/controllers/history_controller.rb
class HistoryController < SecureController
  def index
    @ideas = current_project.ideas.order("title ASC")
  end
end

app/helpers/history_helper.rb
module HistoryHelper
  def favorite_img idea
    if current_user.favorite_idea? idea
      image_tag "star-checked.png", :alt => 'favorite', "data-idea-id" => idea.id
    else
      image_tag "star-unchecked.png", :alt => 'not favorite', "data-idea-id" => idea.id
    end
  end

  def get_unfilled_stars idea
    Rating.max_rating - idea.get_rating_for_user(current_user)
  end

  def get_average_unfilled_stars idea
    Rating.max_rating - idea.average_rating
  end

  def format_created_by created_by
    return '' if created_by.nil?
    created_by.sub /@.*/, ''
  end

  def format_date time
    return "" if time.nil?
    time.strftime("%m/%d/%y %I:%M %p")
  end

  def format_title title, length=50
    content_tag 'span', truncate(title, :length => length), :title => title
  end

  def format_description description
    content_tag 'span', description, :title => description
  end

end

app/views/history/_form.html.haml
#idea_form.modal{:style => 'display:none; top:300px;'}
  .modal-header
    %a.close{:href => '#'}x
    %h3.title
  .modal-body
    =form_for :idea, :method => :put, :html => {:class => 'form-stacked'} do |f|
      %fieldset
        .clearfix.created_by
          != f.label :created_by
          != f.text_field :created_by, :class => 'span8'
          %span.help-inline
        .clearfix.title
          != f.label :title
          != f.text_field :title, :class => 'span8'
          %span.help-inline
        .clearfix.description
          != f.label :description
          != f.text_area :description, :class => 'span8'
          %span.help-inline
        .clearfix.category
          != f.label :category
          != f.select :category, (Category.all.collect {|c| [c.name, c.id]}), :class => 'span8'
          %span.help-inline
  .modal-footer
    != link_to 'Delete', '#', :method => :delete, :confirm => 'Are you sure you want to delete this idea?', :class => 'btn btn-danger delete_button'
    %button.btn.btn-primary.ajaxd Save

app/views/history/_idea.html.haml
%tr
  %td.favorite
    = favorite_img idea
  %td.title
    != link_to_function format_title(idea.title), "openIdea('#{project_idea_path(idea.project, idea)}')"
  %td.description{:style => 'display:none;'}
    != format_description(idea.description)
  %td.created_at
    != format_date(idea.created_at)
  %td.created_by
    != format_created_by(idea.created_by)
  %td.category
    != idea.category.name unless idea.category.nil?
  %td.rating
    - idea.get_rating_for_user(current_user).times do |star_num|
      = image_tag "star-rating-filled.png", :alt => idea.get_rating_for_user(current_user), "data-star-num" => star_num + 1, "data-idea-id" => idea.id
    - get_unfilled_stars(idea).times do |star_num|
      = image_tag "star-rating-unfilled.png", "data-star-num" => star_num + 1 + idea.get_rating_for_user(current_user), "data-idea-id" => idea.id
  %td.avg_rating
    - idea.average_rating.times do |star_num|
      = image_tag "star-rating-filled.png", :alt => idea.average_rating
    - get_average_unfilled_stars(idea).times do |star_num|
      = image_tag "star-rating-unfilled.png"
  %td.comments
    != link_to pluralize(idea.comments.size, "comment"), project_idea_comments_path(idea.project, idea)