config/routes.rb
Ideas::Application.routes.draw do

  resources :categories, :except => :show

  resources :projects, :except => :show do
    resources :ideas do
      resources :comments, :only => [:index, :create, :new]
    end

    resources :memberships, :only => [:index, :destroy, :create]
    get '/history' => 'history#index'
    get '/settings' => 'settings#edit', :as => :edit_settings
    post '/settings' => 'settings#update', :as => :update_settings
  end
  post '/membership/update' => 'memberships#update'
  post '/project/update/idea' => 'projects#update_project_idea'
  get '/ideas' => 'ideas#view_all'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get "users/sign_out" => "devise/sessions#destroy"
  end

  match '/incoming_mail' => 'incoming_mail#create'
  match '/new_favorite' => 'favorite_ideas#create', :as => 'new_favorite'
  match '/delete_favorite' => 'favorite_ideas#delete', :as => 'delete_favorite'
  match '/rating' => 'ratings#rate', :as => 'rate_idea'
  root :to => 'front#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, :presence => true, :length => { :maximum => 255 }
  has_many :ideas, :dependent => :destroy

  has_many :memberships, :dependent => :destroy
  has_many :users, :through => :memberships

  def add_all_users
    self.users = User.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < SecureController
  def index
    @projects = current_user.projects.order("name ASC")
    @memberships = current_user.memberships
  end

  def new
    @project = Project.new
  end

  def edit
    @project = current_user.projects.find(params[:id])
  end

  def create
    membership = params[:project].delete(:memberships)

    @project = current_user.projects.create(params[:project])

    if @project.persisted?
      flash[:notice] = "Project #{@project.name} added!"
    end

    if membership == "2"
      @project.add_all_users
    end
    redirect_to :action => :index
  end

  def update
    @project = current_user.projects.find(params[:id])

    if @project.update_attributes(params[:project])
      flash[:notice] = "Project #{@project.name} updated!"
    end
    redirect_to :back
  end

  def update_project_idea
    @project = Project.find(params[:project][:id])
    @idea = Idea.find(params[:project][:idea][:id])
    @idea.update_attributes(:project => @project)
    render :nothing => true
  end

  def destroy
    project_name = current_user.projects.find(params[:id]).name
    current_user.projects.find(params[:id]).destroy
    flash[:notice] = "Project #{project_name} deleted!"
    redirect_to projects_url
  end
end

app/views/projects/_collapsed_table.html.haml
.table-div{:style => 'width:100%; display:none;'}
  %table.project-table.table.table-striped.table-condensed{:data => { :pid => "#{project.id}", :hidden => "true"}}
    %thead
      %th.favorite{:style => 'width:25px'}
      %th.title{:style => 'width:150px'} Title
      %th.created_at{:style => 'width:130px'} Created At
      %th.created_by{:style => 'width:100px'} Created By
      %th.category{:style => 'width:100px'} Category
      %th.rating Rating
      %th.avg_rating Avg. Rating
      %th.comments{:style => 'width:80px'}
    %tbody
      = render :partial => 'idea', :collection => project.ideas.order("title ASC")

app/views/projects/_expanded_table.html.haml
.table-div{:style => 'width:100%;'}
  %table.project-table.table.table-striped.table-condensed{:data => { :pid => "#{project.id}", :hidden => "false"}}
    %thead
      %th.favorite{:style => 'width:25px'}
      %th.title{:style => 'width:150px'} Title
      %th.created_at{:style => 'width:130px'} Created At
      %th.created_by{:style => 'width:100px'} Created By
      %th.category{:style => 'width:100px'} Category
      %th.rating Rating
      %th.avg_rating Avg. Rating
      %th.comments{:style => 'width:80px'}
    %tbody
      = render :partial => 'idea', :collection => project.ideas.order("title ASC")

app/views/projects/_form.html.haml
= form_for @project, :html => {:class => 'form-stacked'} do |f|
  - if @project.errors.any?
    #error_explanation
      %h2
        = pluralize(@project.errors.count, "error") 
        prohibited this project from being saved:
      %ul
        - @project.errors.full_messages.each do |msg|
          %li
            = msg

  %fieldset
    = f.label :name
    = f.text_field :name
    .radio-input
      = f.radio_button(:memberships, "1")
      = f.label('1', "Only add me to this project for now")
    .radio-input
      = f.radio_button(:memberships, "2", :checked => true)
      = f.label('2', "Add everyone to this project")

  = f.submit 'Create Project', :class => 'btn btn-primary'

app/views/projects/_idea_form.html.haml
#idea_form.modal.hide{:style => 'top:300px;'}
  .modal-header
    %a.close{:href => '#'}x
    %h3.title
  .modal-body
    =form_for :idea, :method => :put, :html => {:class => 'form-stacked'} do |f|
      %fieldset
        .created_by
          != f.label :created_by
          != f.text_field :created_by, :class => 'span6'
          %span.help-inline
        .title
          != f.label :title
          != f.text_field :title, :class => 'span6'
          %span.help-inline
        .description
          != f.label :description
          != f.text_area :description, :size =>'50x8', :class => 'span6'
          %span.help-inline
        .category
          != f.label :category
          != f.select :category, (Category.all.collect {|c| [c.name, c.id]}), {:class => 'span6'}, {:style =>"width:460px;"}
          %span.help-inline
  .modal-footer
    != link_to 'Delete', '#', :method => :delete, :confirm => 'Are you sure you want to delete this idea?', :class => 'btn btn-danger delete_button'
    %button.btn.btn-primary.ajaxd Save

app/views/projects/_new_idea.html.haml
.modal.hide{:id => 'ideaModal'+project.id.to_s}
  .modal-header
    %button.close{:data=> {:dismiss=>"modal"}}
      x
    %h3= "Submit a new idea"

  =form_for Idea.new, :url => project_ideas_path(project.id), :method => 'post', :html => {:data =>{:proj_id => project.id.to_s}} do |f|
    .modal-body
      %fieldset
        .title
          != f.label :title
          != f.text_field :title, :class => 'span6'
          %span.help-inline
        .description
          != f.label :description
          != f.text_area :description, :size =>'50x10', :class => 'span6'
          %span.help-inline
        .category
          != f.label :category
          != f.select :category, (Category.all.collect {|c| [c.name, c.id]}), {:class => 'span6'}, {:style =>"width:460px;"}
          %span.help-inline
    .modal-footer
      != link_to 'Cancel', '#', :class => "btn submit-button-secondary submit-button-delete", :data=> {:dismiss=>"modal"}
      != f.submit 'Create', :class => 'btn btn-primary create_idea_button'

app/views/projects/_settings_form.html.haml
.modal.hide{:id => 'settingsModal'+project.id.to_s}
  .modal-header
    %button.close{:data=> {:dismiss=>"modal"}}
      x
    %h3= "Project Settings"

  .modal-body
    %h3 Project Name
    =form_tag(project_update_settings_path(project), :method => :post) do
      %fieldset
        %div{:class => div_class(project, :name)}
          = text_field_tag :name, project.name
          %span.help-inline
            = inline_help project, :name
          = submit_tag 'Save', :class => 'btn btn-primary'

    %h3 Collaborators
    %table
      - project.memberships.each do |membership|
        %tr
          %td= membership.user.email
          %td= link_to 'Remove', [project, membership], confirm: 'Are you sure?', :method => :delete
    = form_for [project, project.memberships.build], :html => {:class => 'form-stacked'} do |f|
      %fieldset
        = f.label :user, "Enter collaborator's email:"
        = f.text_field :user, :value => (f.object.user.blank? ? '' : f.object.user.email)
        = f.submit 'Add Collaborator', :class => 'btn btn-primary'

  .modal-footer
    = link_to "Delete this project", project_path(project), :confirm => "Are you sure?", :method => :delete, :class => 'btn btn-danger'
    = link_to 'Cancel', '#', :class => "btn submit-button-secondary submit-button-delete", :data=> {:dismiss=>"modal"}

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/index.html.haml
- content_for :head do
  != stylesheet_link_tag 'print', :media => 'print'

%h2
  Ideas by Project
%form
  Search:
  %input{:type => "text", :id => "search"}

- if !@projects.empty?
  %ul
    - @projects.each do |project|
      %div{:id =>"project-div-"+project.id.to_s}
        .project_name_div{:style => "float:left; width:460px;"}
          %h2.click-to-edit
            = project.name
          = form_for project, :remote => true, :html => {:class => "hidden project-form"} do |f|
            = f.text_field :name, :class => "h2", :style => "width:420px;"
            = f.submit 'Update', :class => "btn hidden"

        -# button group of actions on project
        .btn-group{:style => "float:right; width:106px;"}
          %a{:href => "#settingsModal"+project.id.to_s, :class =>"btn settings-button",
                       :data => {:toggle=>"modal", :proj_id => project.id}}
            %b.icon-cog

          %a{:href => "#ideaModal"+project.id.to_s, :class =>"btn new-idea-modal",
                        :data => {:toggle=>"modal", :proj_id => project.id}}
            %b.icon-plus

          .btn.hide-button{:data => {:proj_id => project.id}}
            - if @memberships.where(:project_id => project.id).first.collapsed == true
              %b.icon-chevron-down
            - else
              %b.icon-chevron-up

        = render :partial => 'new_idea', :locals => {:project => project}
        = render :partial => 'settings_form', :locals => {:project => project}

        - if @memberships.where(:project_id => project.id).first.collapsed == true
          = render :partial => 'collapsed_table', :locals =>{:project => project}
        - else
          = render :partial => 'expanded_table', :locals =>{:project => project}



  = render :partial => 'idea_form', :locals => {:all_fields => true}

app/views/projects/new.html.haml
%h1 New project
= render 'form'
= link_to 'Back', projects_path